import { useParams, Link } from "wouter";
import { useStore } from "@/lib/store";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Download, ShieldAlert, BadgeCheck, Clock, FileText, ArrowLeft, RefreshCw, CheckCircle2 } from "lucide-react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { useRef } from "react";
import { toast } from "@/hooks/use-toast";

export default function Report() {
  const { id } = useParams();
  const claim = useStore(state => state.claims.find(c => c.id === id));
  const reportRef = useRef<HTMLDivElement>(null);

  if (!claim) {
    return <div className="p-8 text-center min-h-screen flex flex-col justify-center items-center bg-slate-50"><h2 className="text-3xl font-bold text-slate-800 mb-4">Claim not found</h2><Link href="/"><Button size="lg">Go Home</Button></Link></div>;
  }

  const handleDownloadPDF = async () => {
    if (!reportRef.current) return;
    try {
      toast({ title: "Generating PDF...", description: "Please wait while we prepare your report." });
      
      const element = reportRef.current;
      const canvas = await html2canvas(element, { 
        scale: 2, 
        useCORS: true,
        logging: false,
        backgroundColor: "#ffffff"
      });
      
      const imgData = canvas.toDataURL("image/jpeg", 0.95);
      const pdf = new jsPDF({
        orientation: "p",
        unit: "mm",
        format: "a4"
      });
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      
      const finalWidth = imgWidth * ratio;
      const finalHeight = imgHeight * ratio;
      
      pdf.addImage(imgData, "JPEG", 0, 0, finalWidth, finalHeight);
      pdf.save(`ClaimAgent_Report_${claim.id}.pdf`);
      toast({ title: "Success", description: "PDF downloaded successfully." });
    } catch (error) {
      console.error("PDF Error:", error);
      toast({ title: "Error", description: "Failed to generate PDF. Downloading JSON as fallback.", variant: "destructive" });
      
      // Fallback: Download JSON
      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(claim, null, 2));
      const downloadAnchorNode = document.createElement('a');
      downloadAnchorNode.setAttribute("href", dataStr);
      downloadAnchorNode.setAttribute("download", `ClaimAgent_Report_${claim.id}.json`);
      document.body.appendChild(downloadAnchorNode);
      downloadAnchorNode.click();
      downloadAnchorNode.remove();
    }
  };

  const getStatusColor = (status: string) => {
    if (status === "Pre-Approved" || status === "Finalized") return "bg-green-50 text-green-700 border-green-200";
    if (status === "Under Manual Review") return "bg-amber-50 text-amber-700 border-amber-200";
    return "bg-blue-50 text-blue-700 border-blue-200";
  };

  return (
    <div className="min-h-screen bg-slate-100 py-12 px-4">
      <div className="max-w-5xl mx-auto space-y-8">
        <div className="flex items-center justify-between">
          <Link href="/customer">
            <Button variant="ghost" className="text-slate-600 hover:text-slate-900"><ArrowLeft className="w-5 h-5 mr-2" /> Start New Claim</Button>
          </Link>
          <Button onClick={handleDownloadPDF} size="lg" className="bg-slate-900 hover:bg-slate-800 text-white shadow-lg">
            <Download className="w-5 h-5 mr-2" /> Download PDF Report
          </Button>
        </div>

        {/* This div is the target for PDF generation */}
        <div ref={reportRef} className="bg-white rounded-2xl shadow-2xl overflow-hidden border border-slate-200">
          {/* Header */}
          <div className="bg-primary/5 p-10 border-b border-primary/10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
            <div>
              <div className="flex items-center gap-3 text-primary mb-2">
                <FileText className="w-10 h-10" />
                <h1 className="text-4xl font-bold tracking-tight">Claim Assessment Report</h1>
              </div>
              <p className="text-slate-600 font-medium text-lg">Generated by ClaimAgent AI Engine</p>
            </div>
            <div className="text-left md:text-right bg-white p-4 rounded-xl shadow-sm border border-slate-100">
              <p className="text-sm text-slate-500 uppercase tracking-wider font-semibold mb-1">Claim Reference ID</p>
              <p className="text-2xl font-mono font-bold text-slate-900">{claim.id}</p>
              <p className="text-sm text-slate-500 mt-2">{new Date(claim.date).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</p>
            </div>
          </div>

          <div className="p-10 space-y-10">
            {/* Top Status Row */}
            <div className="flex flex-wrap gap-4">
              <div className={`px-6 py-3 rounded-xl border-2 font-bold flex items-center gap-3 text-lg ${getStatusColor(claim.status)}`}>
                {claim.status === "Pre-Approved" ? <BadgeCheck className="w-6 h-6" /> : <RefreshCw className="w-6 h-6" />}
                Decision: {claim.status}
              </div>
              <div className="px-6 py-3 rounded-xl border border-slate-200 bg-slate-50 font-bold flex items-center gap-3 text-slate-700 text-lg">
                <ShieldAlert className="w-6 h-6 text-primary" />
                AI Confidence: {claim.aiConfidence}%
              </div>
              <div className="px-6 py-3 rounded-xl border border-slate-200 bg-slate-50 font-bold flex items-center gap-3 text-slate-700 text-lg">
                <Clock className="w-6 h-6 text-slate-500" />
                Est. Repair Time: {claim.repairDuration}
              </div>
            </div>

            {/* Vehicle Info */}
            <div>
              <h3 className="text-xl font-bold border-b-2 border-slate-100 pb-3 mb-6 text-slate-800 flex items-center gap-2">
                <span className="w-2 h-6 bg-primary rounded-full inline-block"></span> Vehicle Information
              </h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-base bg-slate-50 p-6 rounded-xl border border-slate-100">
                <div><p className="text-slate-500 mb-1 text-sm uppercase tracking-wider font-semibold">Brand</p><p className="font-bold text-lg">{claim.vehicle.brand}</p></div>
                <div><p className="text-slate-500 mb-1 text-sm uppercase tracking-wider font-semibold">Model</p><p className="font-bold text-lg">{claim.vehicle.model} {claim.vehicle.variant}</p></div>
                <div><p className="text-slate-500 mb-1 text-sm uppercase tracking-wider font-semibold">Year</p><p className="font-bold text-lg">{claim.vehicle.year}</p></div>
                <div><p className="text-slate-500 mb-1 text-sm uppercase tracking-wider font-semibold">Policy No.</p><p className="font-bold text-lg font-mono text-primary">{claim.vehicle.policyNumber}</p></div>
              </div>
            </div>

            {/* Damage Analysis */}
            <div>
               <h3 className="text-xl font-bold border-b-2 border-slate-100 pb-3 mb-6 text-slate-800 flex items-center gap-2">
                <span className="w-2 h-6 bg-amber-500 rounded-full inline-block"></span> Detected Damages
              </h3>
              <div className="border border-slate-200 rounded-xl overflow-hidden">
                <Table>
                  <TableHeader className="bg-slate-50">
                    <TableRow>
                      <TableHead className="font-bold text-slate-700 py-4 px-6 text-base">Part Affected</TableHead>
                      <TableHead className="font-bold text-slate-700 py-4 px-6 text-base">Damage Type</TableHead>
                      <TableHead className="font-bold text-slate-700 py-4 px-6 text-base">Severity Assessment</TableHead>
                      <TableHead className="font-bold text-slate-700 py-4 px-6 text-base text-right">AI Confidence</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {claim.damages.map((d, i) => (
                      <TableRow key={i} className="border-b border-slate-100 last:border-0">
                        <TableCell className="font-bold text-slate-800 px-6 py-4 text-base">{d.part}</TableCell>
                        <TableCell className="px-6 py-4 text-base">{d.type}</TableCell>
                        <TableCell className="px-6 py-4">
                          <span className={`px-3 py-1 rounded-full text-sm font-bold ${
                            d.severity === 'Severe' ? 'bg-red-100 text-red-700' :
                            d.severity === 'Medium' ? 'bg-orange-100 text-orange-700' :
                            'bg-green-100 text-green-700'
                          }`}>
                            {d.severity}
                          </span>
                        </TableCell>
                        <TableCell className="text-right font-bold text-slate-700 px-6 py-4 text-base">{d.confidence}%</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </div>

            {/* Cost Breakdown & Fraud */}
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <h3 className="text-xl font-bold border-b-2 border-slate-100 pb-3 mb-6 text-slate-800 flex items-center gap-2">
                  <span className="w-2 h-6 bg-red-500 rounded-full inline-block"></span> Fraud Assessment
                </h3>
                <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 shadow-sm h-[250px] flex flex-col justify-center">
                  <div className="flex justify-between items-center mb-6">
                    <span className="text-slate-600 font-semibold text-lg">AI Risk Score</span>
                    <span className={`font-black text-2xl px-4 py-1 rounded-lg ${claim.aiRiskScore === 'Low' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                      {claim.aiRiskScore} RISK
                    </span>
                  </div>
                  <ul className="text-base space-y-3 text-slate-600 font-medium">
                    <li className="flex items-center gap-3"><CheckCircle2 className="w-5 h-5 text-green-500"/> EXIF Data Timestamps Valid</li>
                    <li className="flex items-center gap-3"><CheckCircle2 className="w-5 h-5 text-green-500"/> No duplicate image signatures found</li>
                    <li className="flex items-center gap-3"><CheckCircle2 className="w-5 h-5 text-green-500"/> Policy active and valid</li>
                  </ul>
                </div>
              </div>

              <div>
                <h3 className="text-xl font-bold border-b-2 border-slate-100 pb-3 mb-6 text-slate-800 flex items-center gap-2">
                  <span className="w-2 h-6 bg-green-500 rounded-full inline-block"></span> Cost Estimate
                </h3>
                <div className="bg-slate-900 p-6 rounded-xl text-white shadow-lg h-[250px] flex flex-col justify-between">
                  <div className="space-y-2 text-base text-slate-300">
                    <div className="flex justify-between"><span>Parts Cost</span><span className="font-medium text-white">₹{claim.estimate.parts.toLocaleString()}</span></div>
                    <div className="flex justify-between"><span>Paint Cost</span><span className="font-medium text-white">₹{claim.estimate.paint.toLocaleString()}</span></div>
                    <div className="flex justify-between"><span>Labor Cost</span><span className="font-medium text-white">₹{claim.estimate.labor.toLocaleString()}</span></div>
                  </div>
                  
                  <div className="pt-4 space-y-3 mt-4 border-t border-slate-700">
                    <div className="flex justify-between text-slate-400"><span>Policy Deductible</span><span>- ₹{claim.estimate.deductible.toLocaleString()}</span></div>
                    <div className="flex justify-between text-xl font-bold text-green-400">
                      <span>Insurance Payable</span><span>₹{claim.estimate.insurancePayable.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between text-xl font-bold text-white mt-1">
                      <span>Customer Payable</span><span>₹{claim.estimate.customerPayable.toLocaleString()}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}